defaults: &defaults
  currencies:
    - code: USD
      name: US Dollar
    - code: EUR
      name: Euro
    - code: AFN
      name: Afghan Afghani
    - code: ALL
      name: Albanian Lek
    - code: DZD
      name: Algerian Dinar
    - code: AOA
      name: Angolan Kwanza
    - code: ARS
      name: Argentine Peso
    - code: AMD
      name: Armenian Dram
    - code: AWG
      name: Aruban Florin
    - code: AUD
      name: Australian Dollar
    - code: AZN
      name: Azerbaijani Manat
    - code: BSD
      name: Bahamian Dollar
    - code: BHD
      name: Bahraini Dinar
    - code: BDT
      name: Bangladeshi Taka
    - code: BBD
      name: Barbadian Dollar
    - code: BYN
      name: Belarusian Ruble
    - code: BZD
      name: Belize Dollar
    - code: BMD
      name: Bermudan Dollar
    - code: BOB
      name: Bolivian Boliviano
    - code: BWP
      name: Botswanan Pula
    - code: BRL
      name: Brazilian Real
    - code: BND
      name: Brunei Dollar
    - code: BGN
      name: Bulgarian Lev
    - code: BIF
      name: Burundian Franc
    - code: XPF
      name: CFP Franc
    - code: KHR
      name: Cambodian Riel
    - code: CAD
      name: Canadian Dollar
    - code: CVE
      name: Cape Verdean Escudo
    - code: KYD
      name: Cayman Islands Dollar
    - code: CLP
      name: Chilean Peso
    - code: COP
      name: Colombian Peso
    - code: KMF
      name: Comorian Franc
    - code: CDF
      name: Congolese Franc
    - code: BAM
      name: Bosnia-Herzegovina Convertible Mark
    - code: NIO
      name: Nicaraguan Córdoba
    - code: CRC
      name: Costa Rican Colón
    - code: HRK
      name: Kuna
    - code: CUP
      name: Cuban Peso
    - code: CZK
      name: Czech Republic Koruna
    - code: DKK
      name: Danish Krone
    - code: DJF
      name: Djiboutian Franc
    - code: DOP
      name: Dominican Peso
    - code: XCD
      name: East Caribbean Dollar
    - code: EGP
      name: Egyptian Pound
    - code: SVC
      name: Salvadoran Colón
    - code: ETB
      name: Ethiopian Birr
    - code: FKP
      name: Falkland Islands Pound
    - code: FJD
      name: Fijian Dollar
    - code: XAF
      name: CFA Franc BEAC
    - code: GMD
      name: Gambian Dalasi
    - code: GEL
      name: Georgian Lari
    - code: GHS
      name: Ghanaian Cedi
    - code: GIP
      name: Gibraltar Pound
    - code: GTQ
      name: Guatemalan Quetzal
    - code: GNF
      name: Guinean Franc
    - code: GYD
      name: Guyanaese Dollar
    - code: HTG
      name: Haitian Gourde
    - code: HNL
      name: Honduran Lempira
    - code: HKD
      name: Hong Kong Dollar
    - code: UAH
      name: Ukrainian Hryvnia
    - code: HUF
      name: Hungarian Forint
    - code: ISK
      name: Icelandic Króna
    - code: INR
      name: Indian Rupee
    - code: IDR
      name: Indonesian Rupiah
    - code: IRR
      name: Iranian Rial
    - code: IQD
      name: Iraqi Dinar
    - code: JMD
      name: Jamaican Dollar
    - code: JPY
      name: Japanese Yen
    - code: JOD
      name: Jordanian Dinar
    - code: KZT
      name: Kazakhstani Tenge
    - code: KES
      name: Kenyan Shilling
    - code: LAK
      name: Laotian Kip
    - code: KWD
      name: Kuwaiti Dinar
    - code: MMK
      name: Myanma Kyat
    - code: KGS
      name: Kyrgystani Som
    - code: LBP
      name: Lebanese Pound
    - code: SLL
      name: Sierra Leonean Leone
    - code: LSL
      name: Lesotho Loti
    - code: LRD
      name: Liberian Dollar
    - code: LYD
      name: Libyan Dinar
    - code: MOP
      name: Macanese Pataca
    - code: MKD
      name: Macedonian Denar
    - code: MGA
      name: Malagasy Ariary
    - code: MWK
      name: Malawian Malawi Kwacha
    - code: MYR
      name: Malaysian Ringgit
    - code: MVR
      name: Maldivian Rufiyaa
    - code: MRO
      name: Mauritanian Ouguiya
    - code: MUR
      name: Mauritian Rupee
    - code: MXN
      name: Mexican Peso
    - code: MDL
      name: Moldovan Leu
    - code: MNT
      name: Mongolian Tugrik
    - code: MAD
      name: Moroccan Dirham
    - code: MZN
      name: Mozambican Metical
    - code: ERN
      name: Eritrean Nakfa
    - code: NAD
      name: Namibian Dollar
    - code: NPR
      name: Nepalese Rupee
    - code: ANG
      name: Netherlands Antillean Guilder
    - code: ILS
      name: Israeli New Sheqel
    - code: TWD
      name: New Taiwan Dollar
    - code: NZD
      name: New Zealand Dollar
    - code: BTN
      name: Bhutanese Ngultrum
    - code: NGN
      name: Nigerian Naira
    - code: KPW
      name: North Korean Won
    - code: NOK
      name: Norwegian Krone
    - code: OMR
      name: Omani Rial
    - code: PKR
      name: Pakistani Rupee
    - code: PAB
      name: Panamanian Balboa
    - code: PGK
      name: Papua New Guinean Kina
    - code: PYG
      name: Paraguayan Guarani
    - code: PEN
      name: Peruvian Sol
    - code: UYU
      name: Uruguayan Peso
    - code: PHP
      name: Philippine Peso
    - code: PLN
      name: Polish Zloty
    - code: GBP
      name: British Pound Sterling
    - code: QAR
      name: Qatari Rial
    - code: RON
      name: Romanian Leu
    - code: RUB
      name: Russian Ruble
    - code: RWF
      name: Rwandan Franc
    - code: WST
      name: Samoan Tala
    - code: STD
      name: São Tomé and Príncipe Dobra
    - code: SAR
      name: Saudi Riyal
    - code: RSD
      name: Serbian Dinar
    - code: SCR
      name: Seychellois Rupee
    - code: SGD
      name: Singapore Dollar
    - code: SBD
      name: Solomon Islands Dollar
    - code: SOS
      name: Somali Shilling
    - code: ZAR
      name: South African Rand
    - code: KRW
      name: South Korean Won
    - code: SSP
      name: South Sudanese Pound
    - code: LKR
      name: Sri Lankan Rupee
    - code: SHP
      name: Saint Helena Pound
    - code: SDG
      name: Sudanese Pound
    - code: SRD
      name: Suricodese Dollar
    - code: SZL
      name: Swazi Lilangeni
    - code: SEK
      name: Swedish Krona
    - code: CHF
      name: Swiss Franc
    - code: SYP
      name: Syrian Pound
    - code: TJS
      name: Tajikistani Somoni
    - code: TZS
      name: Tanzanian Shilling
    - code: THB
      name: Thai Baht
    - code: TOP
      name: Tongan Paʻanga
    - code: TTD
      name: Trinidad and Tobago Dollar
    - code: TND
      name: Tunisian Dinar
    - code: TRY
      name: Turkish Lira
    - code: TMT
      name: Turkmenistani Manat
    - code: UGX
      name: Ugandan Shilling
    - code: AED
      name: United Arab Emirates Dirham
    - code: UZS
      name: Uzbekistan Som
    - code: VUV
      name: Vanuatu Vatu
    - code: VEF
      name: Venezuelan Bolívar
    - code: VND
      name: Vietcodese Dong
    - code: XOF
      name: CFA Franc BCEAO
    - code: YER
      name: Yemeni Rial
    - code: CNY
      name: Chinese Yuan
    - code: ZMW
      name: ZMW
    - code: ZWL
      name: Zimbabwean Dollar

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
