production:
  :concurrency: 1 # only 1 job is allowed concurrently!
staging:
  :concurrency: 1
development:
  :concurrency: 1
# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8
